version: '3.7'
x-app-settings:
  &app-settings
  restart: always
  build: .

services:
  ocr_server:
    hostname: ocr_server
    container_name: ocr_server
    ports:
      - "9898:9898"
    << : *app-settings

  reverse_proxy:
    image: nginx
    hostname: reverse_proxy
    container_name: reverse_proxy
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/server.crt:/root/server.crt:ro
      - ./nginx/server.key:/root/server.key:ro
    depends_on:
      - ocr_server
